/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.burcu.yatirim.GUI;

import com.burcu.yatirim.dal.MusteriDAO;
import com.burcu.yatirim.models.Musteri;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author cem.unustu
 */
public class frmAnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form frmAnaSayfa
     */
    public frmAnaSayfa() {
        initComponents();
        lblAdYildiz.setVisible(false);
        lblSoyadYildiz.setVisible(false);
        lblTelefonYildiz.setVisible(false);
        lblAdresYildiz.setVisible(false);
    }

    MusteriDAO db = new MusteriDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAnaSayfaAd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAnaSayfaSoyad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnaSayfaAdres = new javax.swing.JTextArea();
        jButtonAnaSayfaIleri = new javax.swing.JButton();
        txtAnaSayfaTelefon = new javax.swing.JFormattedTextField();
        lblAdYildiz = new javax.swing.JLabel();
        lblSoyadYildiz = new javax.swing.JLabel();
        lblTelefonYildiz = new javax.swing.JLabel();
        lblAdresYildiz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yatırım Programı");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Müşteri Bilgileri");

        jLabel2.setText("Ad");

        jLabel3.setText("Soyad");

        jLabel4.setText("Telefon");

        jLabel5.setText("Adres");

        txtAnaSayfaAdres.setColumns(20);
        txtAnaSayfaAdres.setRows(5);
        jScrollPane1.setViewportView(txtAnaSayfaAdres);

        jButtonAnaSayfaIleri.setText("İleri");
        jButtonAnaSayfaIleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAnaSayfaIleriMouseClicked(evt);
            }
        });
        jButtonAnaSayfaIleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaSayfaIleriActionPerformed(evt);
            }
        });

        try {
            txtAnaSayfaTelefon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0(5##)-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblAdYildiz.setForeground(new java.awt.Color(255, 0, 0));
        lblAdYildiz.setText("*");

        lblSoyadYildiz.setForeground(new java.awt.Color(255, 0, 0));
        lblSoyadYildiz.setText("*");

        lblTelefonYildiz.setForeground(new java.awt.Color(255, 0, 0));
        lblTelefonYildiz.setText("*");

        lblAdresYildiz.setForeground(new java.awt.Color(255, 0, 0));
        lblAdresYildiz.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAnaSayfaIleri)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdresYildiz))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtAnaSayfaTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAnaSayfaAd)
                                    .addComponent(txtAnaSayfaSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdYildiz)
                            .addComponent(lblSoyadYildiz)
                            .addComponent(lblTelefonYildiz))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAnaSayfaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdYildiz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAnaSayfaSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoyadYildiz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAnaSayfaTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonYildiz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdresYildiz))
                .addGap(17, 17, 17)
                .addComponent(jButtonAnaSayfaIleri)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnaSayfaIleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaSayfaIleriActionPerformed
        // TODO add your handling code here:
//        new frmAnket().setVisible(true);
//        new frmAnaSayfa().dispose();
    }//GEN-LAST:event_jButtonAnaSayfaIleriActionPerformed

    private void jButtonAnaSayfaIleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnaSayfaIleriMouseClicked
        // TODO add your handling code here:
        boolean isNull = false;
        if (txtAnaSayfaAd.getText().trim().isEmpty()) {
            isNull = true;
            lblAdYildiz.setVisible(true);
            txtAnaSayfaAd.requestFocus();
        }
        if (txtAnaSayfaSoyad.getText().trim().isEmpty()) {
            isNull = true;
            lblSoyadYildiz.setVisible(true);
            txtAnaSayfaSoyad.requestFocus();
        }
        if (txtAnaSayfaAdres.getText().trim().isEmpty()) {
            isNull = true;
            lblTelefonYildiz.setVisible(true);
            txtAnaSayfaAdres.requestFocus();
        }
        if (txtAnaSayfaTelefon.getText().trim().isEmpty()) {
            isNull = true;
            lblAdresYildiz.setVisible(true);
            txtAnaSayfaTelefon.requestFocus();
        }
        if (isNull) {
            JOptionPane.showMessageDialog(null, "Lütfen (*) ile işaretli eksik alanları doldurunuz.", "Hata", JOptionPane.ERROR_MESSAGE);
        } else {

            String ad = txtAnaSayfaAd.getText();

            Musteri mst = new Musteri();
            mst.setAd(txtAnaSayfaAd.getText());
            mst.setSoyad(txtAnaSayfaSoyad.getText());
            mst.setTelefon(txtAnaSayfaTelefon.getText());
            mst.setAdres(txtAnaSayfaAdres.getText());

            db.Save(mst);

            new frmAnketYas().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAnaSayfaIleriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnaSayfaIleri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdYildiz;
    private javax.swing.JLabel lblAdresYildiz;
    private javax.swing.JLabel lblSoyadYildiz;
    private javax.swing.JLabel lblTelefonYildiz;
    private javax.swing.JTextField txtAnaSayfaAd;
    private javax.swing.JTextArea txtAnaSayfaAdres;
    private javax.swing.JTextField txtAnaSayfaSoyad;
    private javax.swing.JFormattedTextField txtAnaSayfaTelefon;
    // End of variables declaration//GEN-END:variables

}
