/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.burcu.yatirim.GUI;

import com.burcu.yatirim.dal.MusteriDAO;

/**
 *
 * @author cem.unustu
 */
public class frmAnketSonuc extends javax.swing.JFrame {

    /**
     * Creates new form frmAnketSonuc
     */
    MusteriDAO db = new MusteriDAO();

    public frmAnketSonuc() {
        initComponents();

        int toplam = db.getToplam();
        jTextField2.setText(String.valueOf(toplam));

        if (toplam >= 0 && toplam <= 20) {
            jRadioButton23.setSelected(true);
        } else if (toplam >= 21 && toplam <= 35) {
            jRadioButton22.setSelected(true);
        } else if (toplam >= 36 && toplam <= 50) {
            jRadioButton24.setSelected(true);
        } else if (toplam >= 51 && toplam <= 75) {
            jRadioButton26.setSelected(true);
        } else if (toplam >= 76 && toplam <= 100) {
            jRadioButton25.setSelected(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabelPuanHesap4 = new javax.swing.JLabel();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        lbl35 = new javax.swing.JLabel();
        lbl74 = new javax.swing.JLabel();
        lblPuan9 = new javax.swing.JLabel();
        lbl75 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl55 = new javax.swing.JLabel();
        lblPuan10 = new javax.swing.JLabel();
        lblPuan11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        lblPuan12 = new javax.swing.JLabel();
        jRadioButton31 = new javax.swing.JRadioButton();
        btnAnketSonuc = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yatırım Değerlendirme");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Test sonucu size uygun bulunan ürün ve hizmetler"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabelPuanHesap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 114, 48, 62));

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        buttonGroup1.add(jRadioButton23);
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        buttonGroup1.add(jRadioButton24);
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        buttonGroup1.add(jRadioButton25);
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        lbl35.setText("<html>Düşük Riskli (Hazine Bonosu, Devlet Tahvili, Hazine Kira Sertifikaları, Yatırımcı  Bilgi Formunda Risk Değeri 2 ve 3 olan yatırım fonları, vb.)</html>");
        jPanel6.add(lbl35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 410, 40));

        lbl74.setText("<html>Çok Yüksek Riskli (Tezgahüstü Türev İşlemler, Yapılandırılmış Borçlanma Araçları, Kaldıraçlı Alım Satım İşlemleri - FX, Yatırımcı Bilgi Formunda Risk Değeri 7 olan  yatırım fonları vb.)</html>");
        jPanel6.add(lbl74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 410, 70));

        lblPuan9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPuan9.setText("Min");
        jPanel6.add(lblPuan9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 40, -1));

        lbl75.setText("<html>Yüksek Riskli (Türev İşlemler (Vadeli İşlem ve Opsiyon Piyasasında), Varant, Yatırım Kuruluşu Sertifikası, Yatırımcı Bilgi Formunda Risk Değeri 5 ve 6 olan  yatırım fonları, vb.)</html>");
        jPanel6.add(lbl75, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 400, -1));

        lbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl22.setText("<html>Çok Düşük Riskli (Repo-Ters Repo, BPP, Yatırımcı Bilgi Formunda Risk Değeri  1 olan yatırım fonları, vb .)</html>");
        lbl22.setToolTipText("");
        lbl22.setAutoscrolls(true);
        lbl22.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel6.add(lbl22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 420, 50));

        lbl55.setText("<html>Orta Riskli (Ortaklık Payı, Eurobond, Dövizli Tahviller, Özel Sektör Borçlanma Araçları, Kira Sertifikaları, Yatırımcı Bilgi Formunda Risk Değeri 4 olan yatırım  fonları, vb.)</html>");
        jPanel6.add(lbl55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 400, 60));

        lblPuan10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPuan10.setText("Uygun");
        jPanel6.add(lblPuan10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 50, -1));

        lblPuan11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPuan11.setText("Max");
        jPanel6.add(lblPuan11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 40, -1));

        jLabel1.setText("0");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jLabel2.setText("20");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 40, -1));

        jLabel3.setText("21");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jLabel4.setText("35");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 40, -1));

        jLabel5.setText("36");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        jLabel6.setText("50");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 40, -1));

        jLabel7.setText("75");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 40, -1));

        jLabel8.setText("51");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        jLabel9.setText("76");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        jLabel10.setText("100");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 40, -1));

        buttonGroup1.add(jRadioButton26);
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        buttonGroup1.add(jRadioButton27);
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        buttonGroup1.add(jRadioButton28);
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        buttonGroup1.add(jRadioButton29);
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        buttonGroup1.add(jRadioButton30);
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        lblPuan12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPuan12.setText("Uygun Değil");
        jPanel6.add(lblPuan12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 80, -1));

        buttonGroup1.add(jRadioButton31);
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        btnAnketSonuc.setText("İleri");
        btnAnketSonuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnketSonucActionPerformed(evt);
            }
        });

        jLabel11.setText("Toplam Puan");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel11)
                .addGap(25, 25, 25)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnketSonuc)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAnketSonuc)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:  
        if(jRadioButton22.isSelected()){
            btnAnketSonuc.setText("İleri");
        }
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton23.isSelected()){
            btnAnketSonuc.setText("İleri");
        }
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton24.isSelected()){
            btnAnketSonuc.setText("İleri");
        }
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton25.isSelected()){
            btnAnketSonuc.setText("İleri");
        }
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton26.isSelected()){
            btnAnketSonuc.setText("İleri");
        }
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton27.isSelected()) {
            btnAnketSonuc.setText("Bitir");
        }
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton28.isSelected()) {
            btnAnketSonuc.setText("Bitir");
        }
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton29.isSelected()) {
            btnAnketSonuc.setText("Bitir");
        }
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton30.isSelected()) {
            btnAnketSonuc.setText("Bitir");
        }
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton31.isSelected()) {
            btnAnketSonuc.setText("Bitir");
        }
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void btnAnketSonucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnketSonucActionPerformed
        // TODO add your handling code here:
        if (btnAnketSonuc.getText().equals("Bitir")) {
            System.exit(0);
        } else {
            new frmAnketHesap().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnAnketSonucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAnketSonuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAnketSonuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAnketSonuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAnketSonuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnketSonuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnketSonuc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPuanHesap4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl55;
    private javax.swing.JLabel lbl74;
    private javax.swing.JLabel lbl75;
    private javax.swing.JLabel lblPuan10;
    private javax.swing.JLabel lblPuan11;
    private javax.swing.JLabel lblPuan12;
    private javax.swing.JLabel lblPuan9;
    // End of variables declaration//GEN-END:variables
}
