/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.burcu.yatirim.GUI;

import com.burcu.yatirim.dal.MusteriDAO;
import com.burcu.yatirim.models.Musteri;

/**
 *
 * @author burcu
 */
public class frmAnketToplam extends javax.swing.JFrame {

    /**
     * Creates new form frmAnket
     */
    public frmAnketToplam() {
        initComponents();
    }

    MusteriDAO db = new MusteriDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonSon = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelPuanHesap3 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        lbl34 = new javax.swing.JLabel();
        lbl54 = new javax.swing.JLabel();
        lbl72 = new javax.swing.JLabel();
        lblPuan6 = new javax.swing.JLabel();
        lblPuan7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 1050));
        setPreferredSize(new java.awt.Dimension(840, 1050));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSon.setText("Son");
        jButtonSon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSonActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSon, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 1325, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Yatırımlarınızı ne kadar süreyle sermaye piyasalarında değerlendirmeyi düşünürsünüz?"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabelPuanHesap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 114, 48, 62));

        lbl21.setText("Kısa Vadeli (0-6 ay)");
        jPanel5.add(lbl21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, -1, -1));

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setText("4");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setText("3");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        buttonGroup1.add(jRadioButton20);
        jRadioButton20.setText("6");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setText("6");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        lbl34.setText("Orta Vadeli (6 – 12 ay)");
        jPanel5.add(lbl34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 84, -1, -1));

        lbl54.setText("Uzun Vadeli (1 − 3 yıl)");
        jPanel5.add(lbl54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 118, 643, -1));

        lbl72.setText("Daha Uzun Vadeli (3 yıldan uzun)");
        jPanel5.add(lbl72, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblPuan6.setText("Puan Karşılığı");
        jPanel5.add(lblPuan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 31, 136, -1));

        lblPuan7.setText("Puan");
        jPanel5.add(lblPuan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 31, 70, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jLabel3.setText("Toplam Puan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 135, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSonActionPerformed
        // TODO add your handling code here:

        Musteri mst = new Musteri();
        
        
        db.Update(mst);

    }//GEN-LAST:event_jButtonSonActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAnketToplam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAnketToplam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAnketToplam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAnketToplam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnketToplam().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSon;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPuanHesap3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl54;
    private javax.swing.JLabel lbl72;
    private javax.swing.JLabel lblPuan6;
    private javax.swing.JLabel lblPuan7;
    // End of variables declaration//GEN-END:variables
}
